# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master", "github-actions" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
    

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - uses: zhulik/redis-action@1.1.0
      with:
        redis version: '5'
        number of databases: 16

    - uses: actions/setup-go@v3
      with:
        go-version: '1.19'
    - run: go test -v -coverprofile=profile.cov ./...

    - uses: shogo82148/actions-goveralls@v1
      with:
        path-to-profile: profile.cov
